# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        lucioleBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       my_provider:
           entity:
               class: lucioleBundle:user


    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login
