<?php

namespace lucioleBundle\Repository;

/**
 * publicityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class publicityRepository extends \Doctrine\ORM\EntityRepository
{
}
