
homepage:
    path:     /
    defaults: { _controller: lucioleBundle:Default:index }

create_luciole:
    path:     /create-luciole
    defaults: { _controller: lucioleBundle:publicity:new }
create_user:
    path:     /create-user
    defaults: { _controller: lucioleBundle:user:new }

delete_luciole:
    path:     /Delete-luciole/{id}
    defaults: { _controller: lucioleBundle:publicity:delete }
delete_user:
    path:     /Delete-user/{id}
    defaults: { _controller: lucioleBundle:user:delete }

update-luciole:
    path:     /update-luciole/{id}
    defaults: { _controller: lucioleBundle:publicity:update }
update-user:
    path:     /update-user/{id}
    defaults: { _controller: lucioleBundle:user:update }

view-luciole:
    path:     /view-luciole/{id}
    defaults: { _controller: lucioleBundle:publicity:view }

show-luciole:
    path:     /show-luciole
    defaults: { _controller: lucioleBundle:publicity:show2 }
show-user:
    path:     /show-users
    defaults: { _controller: lucioleBundle:user:show2 }
login:
    path: /login
    defaults: { _controller: lucioleBundle:Security:login }

luciole_search:
    path:   /search-luciole
    defaults: { _controller: lucioleBundle:publicity:search }
Forgot_luciole:
    path:     /forgot-password
    defaults: { _controller: lucioleBundle:Security:Forgot }
user_registration:
    path:     /register
    defaults: { _controller: lucioleBundle:Registration:register }

contact_luciole:
    path:     /contact
    defaults: { _controller: lucioleBundle:user:contact }
