
homepage:
    path:     /
    defaults: { _controller: lucioleBundle:Default:index }

create_luciole:
    path:     /create-luciole
    defaults: { _controller: lucioleBundle:publicity:new }
create_user:
    path:     /create-user
    defaults: { _controller: lucioleBundle:user:new }

delete_luciole:
    path:     /Delete-luciole/{id}
    defaults: { _controller: lucioleBundle:publicity:delete }
delete_user:
    path:     /Delete-luciole/{id}
    defaults: { _controller: lucioleBundle:user:delete }

update-luciole:
    path:     /update-luciole/{id}
    defaults: { _controller: lucioleBundle:publicity:update }
update-user:
    path:     /update-luciole/{id}
    defaults: { _controller: lucioleBundle:user:update }

view-luciole:
    path:     /view-article/{id}
    defaults: { _controller: lucioleBundle:Article:view }

show-luciole:
    path:     /show-luciole/
    defaults: { _controller: lucioleBundle:publicity:show }
show-user:
    path:     /show-users
    defaults: { _controller: lucioleBundle:user:show }


luciole_search:
    path:   /search-article
    defaults: { _controller: lucioleBundle:Article:search }

